sdss/sdss_access

CHANGELOG.rst, python/sdss_access/sync/__init__.py, python/sdss_access/sync/auth.py, python/sdss_access/sync/baseaccess.py, python/sdss_access/sync/http.py, tests/conftest.py, tests/sync/test_auth.py, tests/sync/test_http.py
This PR fixes #16.  The `HttpAccess` `set_auth` method was never updated to include a `public` option.  I've fixed this.  To prevent `HttpAccess` and `RsyncAccess` from getting out of sync down the line with authentication, I've combined the separate `set_auth` methods into a single one that lives on a new `AuthMixin` class.  I've changed the `Auth.set_netrc` method to raise an `AccessError` if it cannot find a valid `netrc` file.  Also added new tests on `HttpAccess to ensure the public call of `remote` does not fail, and added new tests for the `Auth` class.
=> Fixes http public access bug #16

python/sdss_access/path/path.py, tests/conftest.py, tests/data/paths.yaml, tests/path/test_path.py, tests/sync/test_http.py, tests/sync/test_rsync.py
This PR fixes #18.  Path can now be instantiated off a loaded module.  The order of precedence is an input `release` -> `TREE_VER` -> "sdsswork" as a valid release.   The following loads sdss5 paths
```
module load tree/sdss5
path = Path()
path.full('rsFields', plan='001', observatory='APO')
'/Users/Brian/Work/sdss/sas/sdss5/sandbox/robostrategy/allocations/001/rsFields-001-APO.fits'
```
or to load DR paths
```
module load tree/dr14
path = Path()
path.full('spec-lite', run2d='v5_10_0', plateid=3606, mjd=55182, fiberid=537)
'/Users/Brian/Work/sdss/sas/dr14/eboss/spectro/redux/v5_10_0/spectra/lite/3606/spec-3606-55182-0537.fits'
```
This works if `TREE_VER` is only set within the created environment module files.  You can still dynamically override by calling Path with a release i.e. …
=> Path now accepts a loaded module as a version

python/sdss_access/sync/cli.py, python/sdss_access/sync/http.py, python/sdss_access/sync/stream.py, setup.cfg, tests/sync/test_http.py
This PR addresses #7 and adds a `tqdm` ([tqdm](https://github.com/tqdm/tqdm)) progress bar to rsync and http downloads.  Adds `tqdm>=4.46.0` as a requirement to `sdss_access`.   When used with `http.get`, progress bar displays the progress of the file size download.  When used with `rsync.commit` displays the progress of the number of files processed within the streams.  
STILL TODO
=> Adds progress bar to downloads

python/sdss_access/path/path.py
The plan is to change apStar in tree to use HEALPix, but we'd like to group them by 100s. The healpixgrp() function in sdss_access will help enable a clean way to do that.
=> Added healpixgrp() to path.py

python/sdss_access/path/path.py
We decided to use nside=128 for the APOGEE apStar HEALPix scheme because other the HEALPix directories for the MW midplane would have had too many stars.  At nside=128 we have 196608 HEALPix and it makes more sense to sort them by 1000s than 100s.  So I modified healpixgrp() in path.py to divide healpix by 1000.
=> Update healpixgrp() in path.py to group by 1000 instead of by 100.

CHANGELOG.rst, docs/sphinx/api.rst, docs/sphinx/conf.py, docs/sphinx/index.rst, docs/sphinx/intro.rst, docs/sphinx/path_defs.rst, docs/sphinx/path_evolution.rst, docs/sphinx/paths.rst, python/sdss_access/path/path.py, python/sdss_access/sync/baseaccess.py, setup.cfg, tests/conftest.py, tests/path/test_sdss5.py
This PR fixes #25 and adds support for preserving a user's original python session `os.environ` when instantiating a new `Path`.  `Path` now accepts a `preserve_envvars` keyword which can set to `True` to preserve a users entire original `os.environ`.   Alternatively it can be set to a list of environment variables to preserve only a subset.    `Path` passes the `preserve_envvars` into `tree.replant_tree`, which handles the actual preservation, see https://github.com/sdss/tree/pull/24. Alternatively the `preserve_envvars` parameter can also be set within the custom YAML config file, ~/.config/sdss/sdss_access.yml to permanently set preservation.
=> adds support for preserving users os environment

.bumpversion.cfg, CHANGELOG.rst, python/sdss_access/path/path.py, setup.cfg, tests/path/test_path.py, tests/path/test_sdss5.py
This PR adds tests for the recent `configgrp` change, fixes some other apogee tests that broke, and updates the changelog in prep for a new release.
=> Adds tests for configgrp, prep for new tag

CHANGELOG.rst, python/sdss_access/path/path.py, tests/path/test_sdss5.py
updated path with special functions to flag plates and zero pad fieldIDs for relevant run2d version
=> updated path with special functions to flag plates and zero pad fieldIDs for relevant run2d version

python/sdss_access/path/path.py, tests/path/test_path.py
This PR adds handling for a special function (`component_default`) for mwmVisit/mwmStar products.
It is related to the path definitions pull request, which is here: https://github.com/sdss/tree/pull/43
The PR includes tests for the added function.
=> Add component_default special function for mwmVisit/mwmStar products

.bumpversion.cfg, CHANGELOG.rst, python/sdss_access/path/path.py, setup.cfg, tests/path/test_path.py, tests/path/test_sdss5.py
This PR fixes broken tests, some issues with MWM paths.  It also corrects the broken version with the 2.0.3 tag, releases a new 2.0.4 patch, bumps the main version to 2.0.5dev.
=> Fixing broken tests and mwm paths

CHANGELOG.rst, docs/sphinx/path_defs.rst, docs/sphinx/path_evolution.rst, docs/sphinx/paths.rst, python/sdss_access/path/path.py, python/sdss_access/sync/baseaccess.py, tests/sync/test_access.py
This PR is a quick bug fix to make IPL-1 data products downloadable with sdss_access.
=> Fixes IPL-1 downloads with sdss_access

CHANGELOG.rst, python/sdss_access/path/path.py
Adds a new function `configsubmodule` that generates `098XXX`-like templates for the new `sdsscore` directory structure.
=> Add new configsubmodule function

.bumpversion.cfg, .github/workflows/build.yml, CHANGELOG.rst, README.md, docs/sphinx/conf.py, docs/sphinx/intro.rst, docs/sphinx/path_defs.rst, docs/sphinx/path_evolution.rst, docs/sphinx/paths.rst, python/sdss_access/__init__.py, python/sdss_access/path/changelog.py, python/sdss_access/path/path.py, python/sdss_access/sync/baseaccess.py, python/sdss_access/sync/http.py, setup.cfg, tests/conftest.py, tests/data/paths.yaml, tests/misc/test_docupaths.py, tests/path/test_changelog.py, tests/path/test_path.py, tests/path/test_sdss5.py, tests/roots/test-docupaths/conf.py, tests/roots/test-docupaths/contents.rst, tests/sync/test_access.py, tests/sync/test_auth.py, tests/sync/test_curl.py, tests/sync/test_http.py, tests/sync/test_rsync.py
This PR updates `sdss_access` to work the version `4.0.0` of `tree`.  It bumps the major version, as it introduces breaking changes.  It also fixes the required keywords issue, closes #32.
=> Refactors sdss_access for new tree

python/sdss_access/path/path.py, python/sdss_access/sync/baseaccess.py
generalized the logic for s5cfgs to include the sequence of all ipls to prevent new ipls from being broken or at least fragile.  @havok2063 feel free to edit as you like.
=> generalize the logic for s5cfgs

CHANGELOG.rst, python/sdss_access/path/path.py, setup.cfg, tests/misc/test_docupaths.py, tests/path/test_path.py
This PR fixes #43 and adds support for Path to understand files with `.fz` compression.
=> Add support for fz compression

python/sdss_access/path/path.py, tests/path/test_sdss5.py
Updates to pad_fieldid function to allow for wildcard and string fieldids
=> update pad_fieldid function

python/sdss_access/path/path.py, tests/path/test_sdss5.py
This PR adds a new `tilegrp` method to produce a tile id integer grouping for the LVM DRP outputs.  This will make the SAS structure more navigable.
=> Adds new tilegrp method for LVM

.github/workflows/build.yml, CHANGELOG.rst
This PR closes #33. It updates the test Github Action to use the latest `main` repo of `tree`, rather than the latest PyPi tag.  This allows `sdss_access` to have the latest paths in tree, and pass any new tests, before a tag has been pushed to PyPi.
=> Updates test action to use main tree repo

CHANGELOG.rst, python/sdss_access/sync/rsync.py, tests/sync/test_rsync.py
Closes #52.  This PR fixes a bug when trying to rsync a file that is compressed on disk, but the template path is not compressed.   It adds a wildcard to the end of the initial stream task rsync `source` to ensure it can find compressed files remotely.
```
from sdss_access import Access
access = Access(release="ipl3")
access.remote()
access.add("mwmAllStar", v_astra="0.5.0")
access.set_stream()
access.stream.task
[{'sas_module': 'ipl-3',
'location': 'spectro/astra/0.5.0/summary/mwmAllStar-0.5.0.fits.gz',
'source': 'rsync://sdss5@dtn.sdss.org/ipl-3/spectro/astra/0.5.0/summary/mwmAllStar-0.5.0.fits.gz',
'destination': '/Users/Brian/Work/sdss/sas/ipl-3/spectro/astra/0.5.0/summary/mwmAllStar-0.5.0.fits.gz',
'exists': None}]
```
=> bug fix for rsync on remote compressed file

CHANGELOG.rst, python/sdss_access/path/path.py, tests/path/test_path.py
Closes #48.  This PR adds a new method to the Path, `add_temp_path`, which allows the addition of new temporary path templates into the local Python environment for use in `sdss_access`.  This can be useful when developing new paths in code, when using `sdss_acces` and a tagged version of `tree`.  This lets you add the paths in the interim until they can get properly added into the `tree` product and a new tag made.  They are not persistent and only work for local path stuff only.
You specify a template `name` and `path`.  The `path` must start with an environment variable and if it doesn't exist in the local environment already, you can define it with the `envvar_path` keyword. 
```
from sdss_access import Access
access = Access()
access.add_temp_path("newCalib", …
```
=> Adds option for adding a temporary path

CHANGELOG.rst, docs/sphinx/intro.rst, python/sdss_access/sync/baseaccess.py, tests/sync/test_curl.py, tests/sync/test_rsync.py
This PR closes #55 and adds the option using sdss_access stream downloading if you already have fully resolved urls or filepaths instead of a set of path keyword arguments.  It adds a new method `.add_file` that accepts either a filepath, url, or path location and reconstructs the correct input to stream.  
```
access = Access(release='DR17')
access.remote()
f = '/Users/Brian/Work/sdss/sas/dr17/manga/spectro/redux/v3_1_1/8485/stack/manga-8485-1901-LOGCUBE.fits.gz'
access.add_file(f, input_type='filepath')
access.set_stream()
access.commit()
```
or a resolved url
```
access = Access(release='DR17')
access.remote()
u = 'rsync://dtn.sdss.org/dr17/manga/spectro/redux/v3_1_1/8485/stack/manga-8485-1901-LOGCUBE.fits.gz'
access.add_file(u, input_type='url')
access.set_stream()
access.commit()
```
=> Adds option for adding a resolved url or filepath for stream downloading

CHANGELOG.rst, docs/sphinx/intro.rst, python/sdss_access/sync/baseaccess.py, python/sdss_access/sync/curl.py, python/sdss_access/sync/rsync.py, readthedocs.yml, tests/sync/test_curl.py, tests/sync/test_rsync.py
This PR closes https://github.com/sdss/tree/issues/82.  It enables by default the follow_symlinks options for rsync.  It exposes a new `follow_symlinks` keyword to the `commit` method to allow users to disable it.
=> Adds follow_symlinks options to commit

python/sdss_access/path/path.py, tests/path/test_path.py
This PR closes #68 and closes #67.  It fixes the `check_public_release` function to now return the correct values for the given release, regardless of what the global tree is set to.  It also now fixes the `is_sdss5` method to also return True when a public DR is not yet marked as public.   
This should allow for testing of `sdss_access` for public DRs ahead of the official release, so e.g. notebook tutorials can be written and tested.
=> fixes for when a public DR is not yet public. 

CHANGELOG.rst, python/sdss_access/sync/rsync.py
This PR closes #70.  It adds the `-i`, or `--itemize-changes` option to the rsync command to fix downloads on Mac OS Sequoia.
=> Fixes rsync for mac sequoia

.bumpversion.cfg, .github/workflows/build.yml, .github/workflows/release.yml, CHANGELOG.rst, setup.cfg
The release Github Action was broken as it was using an outdated Python, which has now been removed.
=> Fixes the broken github action
